### ISSUE TITLE
Request for Comment (RFC): The Future of Financial Objects 

### ISSUE THREAD

**Issue by brooklynrob** [finos/finos-fo#38]
The [FINOS Financial Objects ("FO") project](https://fo.finos.org) has existed for several years and is one of FINOS’ oldest projects. 

Our two current lead maintainers of the project (previously the PMC for the FO program, before programs were deprecated), Hammad Akbar of Citi (@HammadNYC) and Johan Sandersson (@donbasuno) of Factset, both have announced they need to step down as leads due to new roles they’ve taken in their respective firms. 

Meanwhile, progress in the project has slowed in the last few months after an active 2018 and 2019, during which time much of the work was focused on 1) modeling [RFQ in the context of an Interest Rate Swap](https://fo.finos.org/docs/objects/rfq), and 2) working on a set of base entity and instrument objects ([see example](https://fo.finos.org/docs/objects/instrument)). The objects developed by the FO project are used in the FDC3 standard and also have been used in production use cases w/ trading workflows that several sell-side FINOS members have created with a couple buy-sides.

Of note and as context, there also has been object modeling work occurring within FINOS beyond FO, specifically and especially in the Alloy pilot project.

Per the discussion had at the FO meeting on July 30, and before we choose new project leads, now would be the right time to affirm whether we should continue a Financial Objects project within FINOS and, if so, what the remit (scope) of that project should be. 

With that context, this is an Request for Comment (RFC), to conclude August 11, in which we’d like to hear input on:

- Should there continue to be a “Financial Objects” project within FINOS?

- If you think the Financial Objects project should continue on, how should the scope and focus change, if at all?

- Does it makes sense to have a “central clearinghouse” project (i.e., “Financial Objects”) that is the de facto place where object modeling / type dictionary type work happens?
    - Alternatively, should modeling be done, as needed, within the scope of other FINOS projects?

- To what degree would it be valuable for the FO project to be an envoy of sorts to similar initiatives and standards bodies in the industry? In other words, can this project be helpful by also knowing the "lay of the land" of other taxonomies, type dictionaries, standards, etc. out there?

- What is the connection/overlap with the work/scope of the Security Reference Data project, and, in particular, the newly launched Currency Reference Data work stream?

- To what degree is FINOS the right venue to define common object/components for the industry?

- Should the two modeling initiatives within [the Alloy pilot](https://alloy.finos.org/docs/roadmap) - the [FX Options](https://github.com/finos/alloy/tree/master/meeting-minutes/fx-options-wg) work steam to extend the existing FX Option model in ISDA CDM, and the Commodity Reference Data work stream - move into FO once Alloy is open sourced, creating a cleaner separation of concerns between the project to build out the Alloy platform (the Alloy project in FINOS) from modeling work that makes use of that platform?

- Overall, how can the work of FO be maximally useful to other FINOS projects as well as other efforts within the industry?

Our intention is to use your feedback here as input to a subsequent FO meeting, to be scheduled for late August, at which we expect to:

- Affirm that FO should continue on as a project (or, instead recommend to the FINOS ED and board that the project be archived, and the project effectively ceased). Provided the group decides FO should live on then additionally at that meeting we will/would...

- Discuss, deliberate, and set a revised remit/scope

- Choose new project maintainers and lead maintainers (If you’re interested in serving as lead or maintainer, please let us know in the comments here too; I believe Daniel Schwartz, an independent consultant active in several FINOS project, and Stephen Murphy, CEO of FINOS member Genesis, have expressed interest to date).

Overall I think the necessary pre-conditions for the FO project to continue on and thrive are:
- A clear scope/remit/charter that connects to specific, targeted, concrete, and pressing problems/opportunities in the industry w/ propensity to create EBITDA measurable value for FINOS members, the community and the wider financial services ecosystem.
- Motivated project lead maintainers, maintainers, and contributors ready to roll up sleeves to commit time, definitions, and code to the project on a sustained basis.

Thank you for taking the time to add your thoughts. 

Rob U

**Comment by jonfreedman** [comment]
We have a real need for an object modelling language which can express OTC instruments at a level that makes sense to traders. That basically boils down to accepted defaults e.g. GBP swap is 6m libor, USD is 3m libor, LCH is the default clearer for both.
I've seen all sorts of ways of expressing this, sometimes via a deep hierarchy, sometimes with a bespoke symbology, sometimes using the Murex concept of generators. None of these are suitable for crossing organisation boundaries.
If Alloy is a solution to this problem, great. I think the fundamental issue with this problem space is that any solution has to be opinionated and that is very hard to do via consensus.

**Comment by dschwartznyc** [comment]
My view is that the existential questions for this project are first what should be its remit and then does that remit warrant continued existence. 

WRT remit - I  believe it is a flawed premise that the project should or can be a central clearing house or standards body for all of FINOS' modelling of financial objects.  That remit is too broad and the project will either end up being a bottleneck, ineffective or both. 

Alternatively, my recommendation is that the group's remit should be to focus on providing modeling / implementation for objects and processes where interoperability is required whether it be between entities, services / service providers, other FINOS projects, et al.    

Under that remit, the project's first task would be, as the RFC cites, to focus on "specific, targeted, concrete and pressing problems / opportunities" which are common enough and significant enough that FINOS members and others in the industry would be prepared to commit or have already committed resources for its resolution.  Project would continue if it can find those problems and get support for their resolution.  If not, it should be dissolved or parked until a later time when more commitment exists. 

This framework would allow other projects which are developing models for common objects (whether in Alloy or otherwise) to roll under the FO project umbrella as long doing that organization was for more than administrative reasons.  If there isn't sufficient synergy those activities should remain standalone.

**Comment by kriswest** [comment]
FDC3 working group have recently discussed the establishment of sufficient standardized types as an important hurdle that must be overcome in order for vendors across the industry to be able to implement the FDC3 desktop agent to integrate with each other without direct coordination with each other. Having worked with several vendors trying to provide support for FDC3 in their products, I've observed that each has had to create their own custom context data types to encode the data their clients need. That necessitates coordination between firms or the implementation of custom translation layers in the desktop agent or downstream in other components, eliminating much of the benefit gain from the API standard.

The FDC3 project doesn't want to get into data modelling specifically, but is heavily dependent on standardised or at least 'well known' context data models to realise the value in its API specifications and achieve widespread uptake. I believe that to be a concrete and pressing problem that could/should either be solved by providing a repository or venue to share context object schemas (from which standards may emerge...) OR by directly producing standards. The later is probably much harder to achieve without the former.

I know there have been past attempts to establish similar standards. Is anyone familiar with the the financial extension from schema.org (https://schema.org/docs/financial.html), which appears largely forcused on accoutns and payments (rather than capital markets and trading) and whether it is/was used anywhere? I'm sure there are many other examples of similar efforts. Do such past efforts point to happy path?

**Comment by nigelcobb** [comment]
REGnosys would be supportive of the Financial Objects project continuing and would welcome the opportunity to contribute resources and tools for the creation of standard data models.
As noted by other contributors it is important to have specific problem statements that the group aims to address. The source of these problem statements can be other FINOS initiatives such as FDC3, trade associations such as ISDA, or from member firms. However for the mandate of the Financial Objects initiative it is important to always maintain this link between sponsorship and deliverables. Significant investment has already been made to develop a common event and product model for financial markets transactions, the Common Domain Model, critical to the success of which has been the sponsorship of ISDA with an initial deliverable focus on the derivatives market. Such ambitious undertaking, of the kind aimed by the Financial Objects initiative, requires sustained industry sponsorship to commit the resources necessary to carry it out.
Assuming this sponsorship is in place the Financial Objects project would be a desirable place to house and clear all modelling discussions, separating out the considerations of platform open sourcing discussions, from modelling concerns. The group would then provide a place where all trade associations could come together to align the strategic direction of industry modelling initiatives, promoting interoperability and alignment while preventing bifurcation of methodology.
REGnosys recognises that one of the first hurdles to adoption is interoperability of data models through a translation layer. Topics previously raised by the working group and in responses so far identify the need for a solution that allows data standards to work together to facilitate integration across industry platforms. Recognising that there is already a growing number of tools used to express data standards, we further propose that the Financial Objects initiative should  drive interoperability amongst existing tooling, by using open-source and freely available software to define a common way of defining data standards, such that conformant models can easily translate across different toolsets. As such, REGnosys can make tooling and expertise available to the group to facilitate and accelerate these discussions, leveraging our track record developing the Common Domain Model and helping integrate it for enterprise use. We urge the FINOS community to lean on existing technology and best practices that are already being developed as part of other, well-established open source initiatives (the Eclipse Modelling Framework being one such).
On a longer term basis, in a scenario where industry standard data models are contributed to FINOS this puts in place the requirement for a strong governance process to maintain and extend models. Dedicated expertise is required on a number of fronts to manage this process, for example hosting of code, project management, modelling capability and modelling expertise. Defining the Financial Objects working group correctly at this stage is important in order to position the group for this potential future phase.

**Comment by lolabeis** [comment]
@mindthegab I will be following-up on this while REGnosys' @nigelcobb is away this week. To this end I'd like to take part in the next FO meeting where this is being discussed (if you can share the invite details offline with me). That said, given that the go / no-go decision seems to be an important one, we should ensure that a critical mass of reps can attend to chime in - it may mean at a later date if key folks are away?

**Comment by lolabeis** [comment]
@mindthegab I have made a further suggestion about use-case for FO under the "sister" Alloy discussion here: https://github.com/finos/community/issues/64#issuecomment-680080603

**Comment by aitana16** [comment]
At the [August 25th Financial Objects meeting](https://github.com/finos/finos-fo/issues/41), a decision was made to keep the FO project infrastructure (i.e. mailing lists, GitHub repo) open and available to the group for asynchronous collaboration. Recurring meetings will be cancelled and meetings will be scheduled on an ad-hoc basis. All meeting attendees were encouraged to sign up to the Financial Objects project mailing list - which can be done by emailing fo+subscribe@finos.org. All communications relevant to the future and potential scope of the project will be carried out through the fo@finos.org mailing list and the GitHub issues raised in the Financial Objects GitHub repo (https://github.com/finos/finos-fo/issues).

**Comment by ffionwiggins** [comment]
On the back of the successful groups run as part of the Legend open sourcing last year, we are keen to set up two new groups to tackle new problem statements. These cover: i) reviewing and enhancing the ISDA CDM for commodities options and ii) creating a common template for product control price dissemination. 

Financial Objects feels the right place to set these up and allows for the expansion into other problem statements over time. 

Based on this, I am happy to host (and hopefully co-host) the Financial Objects project with a broad scope to provide a space for modelling opportunities driving and improving the interactions between parties in the financial industry.

**Comment by donbasuno** [comment]
Hi @ffionwiggins,

I agree with your proposal above and fully support you hosting the FO project. I will continue to work with the FDC3 project which will continue to propose context data standards to FO so we'll definitely cross paths in the future.

Best regards,

Johan

**Comment by agitana** [comment]
Thank you @ffionwiggins for stepping forward to lead the Financial Objects project. Following the support that your proposal has received over the past ten days via the [FINOS community mailing list](https://groups.google.com/a/finos.org/g/community/c/7U3uS0GJ0QQ) and on this GitHub issue, and the lack of objections from the community, we're delighted to confirm that you're the new lead for the FINOS Financial Objects project.

We encourage everyone to engage with the new FO modeling projects: Commodities Payout (commodities-payout@finos.org), and Product Control Common Template (product-control-common-template@finos.org) on the [FO GitHub repository](https://github.com/finos/finos-fo), and to reach out to the project mailing lists with any questions.
